weights: yolov5n-seg.pt
cfg: ''
data: C:\Users\Uib\yolov5\data\fish.yaml
hyp:
  lr0: 0.001
  lrf: 0.01
  momentum: 0.937
  weight_decay: 0.0005
  warmup_epochs: 3.0
  warmup_momentum: 0.8
  warmup_bias_lr: 0.1
  box: 0.05
  cls: 0.5
  cls_pw: 1.0
  obj: 1.0
  obj_pw: 1.0
  iou_t: 0.5
  anchor_t: 4.0
  fl_gamma: 0.0
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  degrees: 0.0
  translate: 0.1
  scale: 0.5
  shear: 0.0
  perspective: 0.0
  flipud: 0.0
  fliplr: 0.5
  mosaic: 0.2
  mixup: 0.0
  copy_paste: 0.0
epochs: 300
batch_size: 8
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: '0'
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: C:\Users\Uib\yolov5\projects\fish\test_sizes\nano
name: C:\Users\Uib\yolov5\projects\fish\test_sizes\nano\fold_4
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 20
freeze:
- 0
save_period: -1
seed: 42
local_rank: -1
mask_ratio: 4
no_overlap: false
save_dir: C:\Users\Uib\yolov5\projects\fish\test_sizes\nano\fold_42
